#############################################################################################
# WoeshBackup config file.
#############################################################################################

# The backupDirPath will be used to put all backups in. This path is relative to the server directory (not the plugins directory). Default: 'woeshBackups'.
backupDirPath: 'woeshBackups'

# The snapshotsDirPath will be used to put all restored backups in (/woeshbackup generatesnapshot). This path is relative to the server directory (not the plugins directory). Default: 'snapshots'.
snapshotsDirPath: 'snapshots'

# Autobackup settings.
autoBackup:
    
    # Enable or disable auto backup. Default: true.
    enabled: true
    
    # If enabled is true, a backup will be made every this amount of time. Example format: 1d12h5m30s. Default: 1h (1 hour).
    interval: 1h

# Used to set the density of backups per backup age interval. This is a list of lists in format: [[interval1, duration1], [interval2, duration2], ...].
# This is used as follows: From now until duration1 time in the past, merge backups such that only one backup per interval1 is kept.
# Then from duration 1 time in the past until duration2 time in the past, do the same for interval2, etc. The maximum backup age is the sum of supplied durations.
# Supply an interval of -1 to never merge in that backup age interval, and supply a duration of -1 to indicate that that duration should be forever.
# Backups older than the sum of durations are merged, unless a duration is -1.
# Intervals and durations are either in seconds or in time format (e.g. 1d12h5m30s). Default: Never merge forever ([[-1, -1]]).
mergeIntervals: [
    [1h, 2w], # Keep one backup per hour for 2 weeks.
    [2h, 30d], # Keep one backup per 2 hours for the next 30 days.
    [1d, 1y], # Keep one backup per day for the next year.
    [1y, -1] # Keep one backup per year until forever.
]

# If less than this amount of disk space is available, no backups will start. The value is in MBs.
dontBackupIfLessThanThisSpaceIsAvailableInMB: 5000

# Enable or disable removal of generated snapshots on plugin enable. Default: true.
removeSnapshotsOnEnable: true

# Enable or disable debug feedback in console. Default: false.
debugEnabled: false
