#############################################################################################
# WoeshBackup config file.
#############################################################################################

# The backupDirPath will be used to put all backups in. This path is relative to the server directory (not the plugins directory). Default: 'woeshBackups'.
backupDirPath: 'woeshBackups'

# The snapshotsDirPath will be used to put all restored backups in (/woeshbackup generatesnapshot). This path is relative to the server directory (not the plugins directory). Default: 'snapshots'.
snapshotsDirPath: 'snapshots'

# Autobackup settings.
autoBackup:
    
    # Enable or disable auto backup. Default: true.
    enabled: true
    
    # If enabled is true, a backup will be made every this amount of time. Example format: 1d12h5m30s. Default: 1h (1 hour).
    interval: 1h

# The time to keep backups. Example format: 1d12h5m30s. Default: 21d (21 days).
maxBackupAge: 21d

# If less than this amount of disk space is available, no backups will start. The value is in MBs.
dontBackupIfLessThanThisSpaceIsAvailableInMB: 5000

# Enable or disable removal of generated snapshots on plugin enable. Default: true.
removeSnapshotsOnEnable: true

# Enable or disable debug feedback in console. Default: false.
debugEnabled: false
