name: WoeshBackup
main: io.github.pieter12345.woeshbackup.bukkit.WoeshBackupPlugin
version: ${version}
author: Pieter12345/Woesh0007
load: postworld
api-version: 1.13
commands:
    woeshbackup:
        description: An incremental backup plugin.
        usage: Type "/woeshbackup help" for help.
        permission: woeshbackup.use
        permission-message: You do not have permission to use this command.
